spring:
   application:
      name: transaction-service
   cloud:
      stream:
         bindings:
            output:
               destination: transactions
server:
   port: 8100
eureka:
   client:
#      registerWithEureka: true
#      fetchRegistry: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka/