spring:
  application:
    name: transaction-service
  cloud:
    stream:
      bindings:
        output:
          destination: transactions
server:
  port: 8100
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
