spring:
  application:
    name: persistence-service
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
  cloud:
    stream:
      bindings:
        input:
          destination: transactions
          group: transactions-group
          durableSubscription: true
server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/