spring:
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
logging:
  level:
    org:
      springframework:
        security: DEBUG